### ISSUE TITLE
Add readme + screenshots

### ISSUE THREAD

**Issue by m-cat** [WammKD/emacs-klere-theme#1]
Hi, I think you should have a readme with some screenshots if you want people to try your theme. I'm curious what this looks like but I don't install packages blindly. Thank you :)

**Comment by WammKD** [comment]
Heh, of course; I've been meaning to but haven't had a chance yet (leastwise, until later today).

In the meantime, it's also on Emacs Themes and there're some screenshots there, if you wanted to see what it looked like: https://emacsthemes.com/themes/klere-theme.html.

**Comment by m-cat** [comment]
Ah, thanks. It looks quite nice!

**Comment by WammKD** [comment]
README.md's been added!
